version: "3.7"

services:
  app:
    image: node
    container_name: vuenode
    ports:
      - 3000:8080
    restart: always
    working_dir: /app
    volumes:
      - /home/andy/vueapp/vue_node:/app
    command: npm run serve